[package]
name = "aoc-2024-17"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-2024-lib = { path = "../lib" }
parse-display = "0.10.0"
smallvec = "1.13"
itertools = "0.12"

[dev-dependencies]
indoc = "2.0"
