[package]
name = "aoc-2024-20"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
aoc-2024-lib = { path = "../lib" }
pathfinding = "4.12.0"
parse-display = "0.10.0"
pretty_assertions = "1.4.1"
